// File generated by Antigravity, mimicking FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb3cd0HVg0-XU3JPvFxRz1xSz6w4PFHNo',
    appId: '1:346974235549:web:b43c15b52416054276dd74',
    messagingSenderId: '346974235549',
    projectId: 'empresa-s',
    authDomain: 'empresa-s.firebaseapp.com',
    storageBucket: 'empresa-s.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZy37i2uZCsM-wCdUd9uuQV3kAycdAP4o',
    appId: '1:346974235549:android:42b468edc1c22cfe76dd74',
    messagingSenderId: '346974235549',
    projectId: 'empresa-s',
    storageBucket: 'empresa-s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZy37i2uZCsM-wCdUd9uuQV3kAycdAP4o',
    appId: '1:346974235549:ios:d070ad8ef2a2eb0876dd74', // Default placeholder or matched pattern
    messagingSenderId: '346974235549',
    projectId: 'empresa-s',
    storageBucket: 'empresa-s.firebasestorage.app',
    iosBundleId: 'com.example.flutter_firebase',
  );
}
